fullName: anchor-platform
namespace: sandbox
service:
   containerPort: 8080
   servicePort: 8080
   type: NodePort
   name: sep
image:
   repo: stellar
   name: anchor-platform
   tag: 022afab
   pullPolicy: Always
deployment:
   replicas: 1
   envFrom:
   - secretRef:
       name: sepsecrets
ingress:
   labels:
     app: appy
     test: label_test
   annotations:
     kubernetes.io/ingress.class: "public"
     cert-manager.io/cluster-issuer: "default"
     ingress.kubernetes.io/ssl-redirect: "true"
     ingress.kubernetes.io/browser-xss-filter: "true"
     ingress.kubernetes.io/frame-deny: "true"
     ingress.kubernetes.io/content-type-nosniff: "true"
     ingress.kubernetes.io/hsts-max-age: "31536000"
     ingress.kubernetes.io/hsts-include-subdomains: "true"
   tls:
     host: "stellaranchordemo.com"
     secretName: anchor-platform-sep-server-cert
   rules:
      hosts:
        - host: "stellaranchordemo.com"
          path: /
          pathType: Prefix
          backend:
            servicePort: "{{ .Values.service.containerPort }}"
            serviceName: "{{ .Values.fullName }}-svc-{{ .Values.service.name }}"
stellar:
   app_config:
      app:
         hostUrl: https://stellaranchordemo.com
         jwtSecretKey:  ${JWT_SECRET}
      sep1:
        enabled: true
        stellarFile: file:/config/stellar-wks.toml
      sep10:
        enabled: true
        homeDomain: stellaranchordemo.com
        signingSeed: ${SEP10_SIGNING_SEED}
      sep12:
        enabled: true
        customerIntegrationEndpoint: https://anchor-reference-server-dev.stellar.org
      sep31:
        enabled: true
        feeIntegrationEndPoint: https://anchor-reference-server-dev.stellar.org
      sep38:
        enabled: true
        quoteIntegrationEndPoint: https://anchor-reference-server-dev.stellar.org
      event:
         enabled: true
         publisherType: kafka
      kafka_publisher:
         bootstrapServer: kafka-broker:9092
