ACCOUNTS = ["GCHLHDBOKG2JWMJQBTLSL5XG6NO7ESXI2TAQKZXCXWXB5WI2X6W233PR"]
VERSION = "0.1.0"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
SIGNING_KEY = "GDAAXJZ6NJFVLYQTZSMBMOY44JVITKMRVPPPZABTMX6S6HDQI66WNK7S"
TRANSFER_SERVER = "https://www.dev.redchapina.com/sep6"
TRANSFER_SERVER_SEP0024 = "https://www.dev.redchapina.com/sep24"
WEB_AUTH_ENDPOINT = "https://www.dev.redchapina.com/auth"
KYC_SERVER = "https://www.dev.redchapina.com/sep12"
DIRECT_PAYMENT_SERVER = "https://www.dev.redchapina.com/sep31"
ANCHOR_QUOTE_SERVER = "https://www.dev.redchapina.com/sep38"

[[CURRENCIES]]
code = "USDC"
issuer = "GCH3RMFPFA7DYESE6GR6YSYOMU6XKSQIUPLQX2DVTX7IXWG24PZEK6P3"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
desc = "A test USDC issued by Circle."

[DOCUMENTATION]
ORG_NAME = "your_org_name1"
ORG_URL = "https://your_org_url.png"
ORG_DESCRIPTION = "your_org_description"
ORG_LOGO = "https://your_org_logo.png"
ORG_SUPPORT_EMAIL = "email@your.org"